### ISSUE TITLE
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window

### ISSUE THREAD

**Issue by davidjrice** [paypal/paypal-here-sdk-android-distribution#102]
Hi folks; we are using the PayPal Here SDK in our integration and are seeing the following exception occurring occasionally.

From Crashlytics "This crash is usually caused by your app trying to display a dialog using a previously-finished Activity as a context. For example, this can happen if an Activity triggers an AsyncTask that tries to display a dialog when it is finished, but the user navigates back from the Activity before the task is completed."

```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@7fd7ef0 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:890)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:377)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:97)
       at android.app.Dialog.show(Dialog.java:401)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity$2.run(EMVDeviceUpdateActivity.java:181)
       at android.app.Activity.runOnUiThread(Activity.java:6058)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity.showSoftwareUpdateSuccessDialog(EMVDeviceUpdateActivity.java:178)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity.access$1300(EMVDeviceUpdateActivity.java:41)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity$ReaderUpdateHandler.onCompleted(EMVDeviceUpdateActivity.java:527)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity$ReaderUpdateHandler.onCompleted(EMVDeviceUpdateActivity.java:373)
       at com.paypal.merchant.sdk.internal.CardReaderManagerImpl.notifyUpdateListener(CardReaderManagerImpl.java:725)
       at com.paypal.merchant.sdk.internal.CardReaderManagerImpl$SoftwareUpdateStatus.run(CardReaderManagerImpl.java:1470)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@385ef62e is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:567)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:272)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
       at android.app.Dialog.show(Dialog.java:298)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity$5.run(EMVDeviceUpdateActivity.java:216)
       at android.app.Activity.runOnUiThread(Activity.java:5247)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity.showSoftwareUpdateFailureDialog(EMVDeviceUpdateActivity.java:213)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity.access$1800(EMVDeviceUpdateActivity.java:41)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity$ReaderUpdateHandler.onCompleted(EMVDeviceUpdateActivity.java:545)
       at com.paypal.merchant.sdk.internal.ui.emv.EMVDeviceUpdateActivity$ReaderUpdateHandler.onCompleted(EMVDeviceUpdateActivity.java:373)
       at com.paypal.merchant.sdk.internal.CardReaderManagerImpl.notifyUpdateListener(CardReaderManagerImpl.java:725)
       at com.paypal.merchant.sdk.internal.CardReaderManagerImpl$DownloadFailedStatus.run(CardReaderManagerImpl.java:1676)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5306)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by ppmtscory** [comment]
Please upgrade to the latest SDK and let us know if you run into any issues.
