### ISSUE TITLE
NullPointerException com.paypal.merchant.sdk.internal.ui.interfaces.SDKTxNavigationFlow.startSignatureActivity

### ISSUE THREAD

**Issue by davidjrice** [paypal/paypal-here-sdk-android-distribution#103]
Hi folks; we are using the PayPal Here SDK in our integration and are seeing the following exception occurring occasionally.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.paypal.merchant.sdk.internal.ui.interfaces.SDKTxNavigationFlow.startSignatureActivity()' on a null object reference
       at com.paypal.merchant.sdk.internal.ui.emv.EMVUITransactionController.handlePayResponse(EMVUITransactionController.java:275)
       at com.paypal.merchant.sdk.internal.ui.SDKUITransactionController$4.onSuccess(SDKUITransactionController.java:228)
       at com.paypal.merchant.sdk.internal.ui.SDKUITransactionController$4.onSuccess(SDKUITransactionController.java:224)
       at com.paypal.merchant.sdk.internal.TransactionManagerImpl$SuccessfulAuthorizeMessage.run(TransactionManagerImpl.java:2289)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by ppmtscory** [comment]
There have been many improvements made with our new SDK.  Please upgrade to the latest SDK and let us know if you run into any issues.
