### ISSUE TITLE
Merchant not initialized anymore

### ISSUE THREAD

**Issue by tkocik92** [paypal/paypal-here-sdk-android-distribution#168]
I am using the PayPal Here SDK with the Sandbox environment and had it implemented in my application for over a year. At some point in the last month, calling `RetailSDK.initializeMerchant` no longer initializes the merchant after login. The account I used worked previously. The only relevant logcat messages I can find are the following:

~~~
E/PayPalRetailSDK:paypalRest: Received error (domain: auth, code: INTERNAL_SERVICE_ERROR, message: , debugId: 6b23e169c1791, details: ) 
E/PayPalRetailSDK:merchant: Merchant initialize failed isOffline: false error: Error 
W/System.err: com.paypal.paypalretailsdk.RetailSDKException: 
W/System.err:     at com.paypal.paypalretailsdk.RetailSDKTypeConverter.asNative(RetailSDKTypeConverter.java:34)
W/System.err:     at com.paypal.paypalretailsdk.RetailSDK$7.invoke(RetailSDK.java:415)
W/System.err:     at com.eclipsesource.v8.V8.callVoidJavaMethod(V8.java:781)
W/System.err:     at com.eclipsesource.v8.V8._executeFunction(Native Method)
W/System.err:     at com.eclipsesource.v8.V8.executeFunction(V8.java:1000)
W/System.err:     at com.eclipsesource.v8.V8Function.call(V8Function.java:80)
W/System.err:     at com.paypal.manticore.NativeServices$1$2.run(NativeServices.java:319)
W/System.err:     at com.paypal.manticore.JsExecutor$4.run(JsExecutor.java:172)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
~~~

The version of the SDK I am using is `2.1.0.201801`

Is there an update I am unaware of to get things working again?

**Comment by tkocik92** [comment]
Closing this issue as the problem is no longer occurring despite not making any changes.
